version: '3.8'

services:
  backend:
    image: shravanychandhanaa/backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - fusiondata:/app/app/data
    networks:
      - fusionpact
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: shravanychandhanaa/frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fusionpact
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - fusionpact

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - fusionpact

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - fusionpact

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
      - "8080:8080"
    networks:
      - fusionpact

volumes:
  fusiondata:
    driver: local

networks:
  fusionpact:
    driver: bridge